main: pw.JA.mobspawn.mobspawn
version: 0.1.14
name: mobspawn
commands:
    AMS:
        description: a nice mod that helps with spawning mobs automaticly
    test:
        description: this is the command for testing
permissions:
    ams:
        description: this is the power permissions for everything
        children: